#! /bin/sh
# Allocates an exclusive node.

if [[ $# -ne 0 ]]; then
    echo "Usage: allocate"
    echo "  Allocates an empty cluster in SLURM"
    exit 1
fi

sbatch \
    --gres=gpu:volta:8 \
    --wrap "sleep 259200" \
    --constraint volta32gb \
    --time 1440 \
    --exclusive \
    --partition dev \
    --mem 500G
