#!/bin/bash
# Script to configure RunPod.

# Install packages.
apt install vim cron ffmpeg tmux zsh

# Removes some initial scripts.
rm -r ~/.bashrc ~/.profile

# Installs Conda.
script_dir="$(dirname "$(readlink -f "$0")")"
${script_dir}/install-conda

# Configures data directory.
echo "Remember to run 'relink-directories <dataset-dir> <checkpoints-dir>'"

