#!/bin/sh
# Moves a directory's contents up one level and deletes the directory.

if [ $# -ne 1 ]; then
    echo "Usage: flatten <directory>"
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "Error: $1 is not a directory"
    exit 1
fi

# Moves the directory to a temporary location.
tmpdir=$(mktemp -d)
fromdir=$tmpdir/$(basename "$1")
mv "$1" "$fromdir"
todir=$(dirname "$1")

# Moves regular files.
for file in $fromdir/*; do
    mv "$file" "$todir"
done

# Moves hidden files.
for file in $fromdir/.*; do
    if [ "$file" != "$fromdir/." ] && [ "$file" != "$fromdir/.." ]; then
        mv "$file" "$todir"
    fi
done

# Removes the temporary directory.
rmdir "$fromdir"
