#!/usr/bin/env python3
"""Prints a random, unused port number."""

import socket


def main() -> None:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("", 0))
    addr = s.getsockname()
    print(addr[1])
    s.close()


if __name__ == "__main__":
    main()
