#!/usr/bin/env python
"""Helper script to run an HTTP server from a given directory."""

import argparse
import http.server
import os
import re
import socket
import socketserver
import threading
import time
from typing import Tuple

TEXT_MIMETYPES: Tuple[str, ...] = ("text/plain", "application/octet-stream")


def get_free_port() -> Tuple[str, int]:
    """Returns an open port to connect to."""

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("", 0))
    addr = s.getsockname()
    port = addr
    s.close()
    return port


def close_server(httpd: socketserver.TCPServer, wait_seconds: int):
    """Closes an active TCP server."""

    time.sleep(wait_seconds)
    print(f"Closing thread after {wait_seconds} seconds")
    httpd.shutdown()


class RequestHandler(http.server.SimpleHTTPRequestHandler):
    """Custom handler for rendering specific filetypes."""

    def end_headers(self) -> None:
        mimetype = self.guess_type(self.path)
        is_file = not self.path.endswith("/")
        if is_file and os.path.exists(path := self.translate_path(self.path)):
            file_bytes = os.stat(path, follow_symlinks=True).st_size
            if mimetype in TEXT_MIMETYPES and file_bytes < 10 * 1024 * 1024:
                self.send_header("Content-Type", "text/plain")
                self.send_header("Content-Disposition", "inline")
        super().end_headers()


def main() -> None:
    """Runs an HTTP server from the current directory."""

    parser = argparse.ArgumentParser(description="Serves an HTTP server.")
    parser.add_argument(
        "-w",
        "--wait-seconds",
        default=60 * 10,
        type=int,
        help="Number of seconds to wait",
    )
    args = parser.parse_args()

    addr, port = get_free_port()
    handler = RequestHandler

    if "SSH_CONNECTION" in os.environ:
        addrs = re.findall(r"((\d+\.){3}\d+)", os.environ["SSH_CONNECTION"])
        if not addrs:
            raise RuntimeError(f"Unexpected {os.environ['SSH_CONNECTION']=}")
        host_addr = addrs[-1][0]
    else:
        host_addr = addr

    with socketserver.TCPServer((addr, port), handler) as httpd:
        print(f"Serving HTTP on {addr} port {port} (http://{host_addr}:{port}) ...")
        thread = threading.Thread(target=close_server, args=(httpd, args.wait_seconds))
        thread.daemon = True
        thread.start()
        httpd.serve_forever()


if __name__ == "__main__":
    main()
